#!/bin/bash
#graspit compilation script
cd qhull
make
cd ..
export GRASPIT=$PWD
export CGDB_MODEL_ROOT=$GRASPIT/cgdb
echo $GRASPIT
echo $CGDB_MODEL_ROOT
#if libraries are not installed on the standard path variable, add them here.
libspaths="\"LIBS+=-L/usr/local/lib\""
qmake $libspaths ./graspit.pro 


make




