# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='Drawable.proto',
  package='',
  serialized_pb='\n\x0e\x44rawable.proto\"\xf1\x04\n\rShapeDrawable\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\r\n\x05width\x18\x03 \x02(\x02\x12\x0e\n\x06height\x18\x04 \x02(\x02\x12\t\n\x01x\x18\x05 \x02(\x02\x12\t\n\x01y\x18\x06 \x02(\x02\x12\x17\n\x0fline_color_argb\x18\x07 \x02(\x05\x12\x12\n\nline_width\x18\x08 \x02(\x02\x12\x37\n\nline_style\x18\t \x01(\x0e\x32\x18.ShapeDrawable.LineStyle:\tSolidLine\x12;\n\x0c\x66ill_pattern\x18\n \x01(\x0e\x32\x1a.ShapeDrawable.FillPattern:\tSolidFill\x12\x17\n\x0f\x66ill_color_argb\x18\x0b \x02(\x05\x12,\n\nshape_type\x18\x0c \x02(\x0e\x32\x18.ShapeDrawable.ShapeType\x12\x0e\n\x04text\x18\r \x01(\t:\x00\"\x9c\x01\n\x0b\x46illPattern\x12\x11\n\rDiagonalLines\x10\x00\x12\x12\n\x0e\x46\x44iagonalLines\x10\x01\x12\x13\n\x0fHorizontalLines\x10\x02\x12\x11\n\rVerticalLines\x10\x03\x12\x10\n\x0c\x43rossedLines\x10\x04\x12\x11\n\rXCrossedLines\x10\x05\x12\r\n\tSolidFill\x10\x06\x12\n\n\x06NoFill\x10\x07\"2\n\tLineStyle\x12\n\n\x06\x44\x61shed\x10\x00\x12\n\n\x06\x44otted\x10\x01\x12\r\n\tSolidLine\x10\x02\":\n\tShapeType\x12\n\n\x06\x43ircle\x10\x00\x12\r\n\tRectangle\x10\x01\x12\x08\n\x04Line\x10\x02\x12\x08\n\x04Text\x10\x03*\x08\x08\x64\x10\x80\x80\x80\x80\x02\"d\n\rDrawableFrame\x12\x14\n\x0c\x66rame_number\x18\x01 \x02(\x05\x12\x1e\n\x06shapes\x18\x02 \x03(\x0b\x32\x0e.ShapeDrawable\x12\x1d\n\x0e\x63learDrawables\x18\x03 \x01(\x08:\x05\x66\x61lse')



_SHAPEDRAWABLE_FILLPATTERN = descriptor.EnumDescriptor(
  name='FillPattern',
  full_name='ShapeDrawable.FillPattern',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='DiagonalLines', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FDiagonalLines', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='HorizontalLines', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VerticalLines', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CrossedLines', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='XCrossedLines', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SolidFill', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NoFill', index=7, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=366,
  serialized_end=522,
)

_SHAPEDRAWABLE_LINESTYLE = descriptor.EnumDescriptor(
  name='LineStyle',
  full_name='ShapeDrawable.LineStyle',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='Dashed', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='Dotted', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SolidLine', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=524,
  serialized_end=574,
)

_SHAPEDRAWABLE_SHAPETYPE = descriptor.EnumDescriptor(
  name='ShapeType',
  full_name='ShapeDrawable.ShapeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='Circle', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='Rectangle', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='Line', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='Text', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=576,
  serialized_end=634,
)


_SHAPEDRAWABLE = descriptor.Descriptor(
  name='ShapeDrawable',
  full_name='ShapeDrawable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='ShapeDrawable.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='ShapeDrawable.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='width', full_name='ShapeDrawable.width', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='height', full_name='ShapeDrawable.height', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='x', full_name='ShapeDrawable.x', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y', full_name='ShapeDrawable.y', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='line_color_argb', full_name='ShapeDrawable.line_color_argb', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='line_width', full_name='ShapeDrawable.line_width', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='line_style', full_name='ShapeDrawable.line_style', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fill_pattern', full_name='ShapeDrawable.fill_pattern', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=6,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fill_color_argb', full_name='ShapeDrawable.fill_color_argb', index=10,
      number=11, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='shape_type', full_name='ShapeDrawable.shape_type', index=11,
      number=12, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='text', full_name='ShapeDrawable.text', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SHAPEDRAWABLE_FILLPATTERN,
    _SHAPEDRAWABLE_LINESTYLE,
    _SHAPEDRAWABLE_SHAPETYPE,
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 536870912), ],
  serialized_start=19,
  serialized_end=644,
)


_DRAWABLEFRAME = descriptor.Descriptor(
  name='DrawableFrame',
  full_name='DrawableFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='frame_number', full_name='DrawableFrame.frame_number', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='shapes', full_name='DrawableFrame.shapes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='clearDrawables', full_name='DrawableFrame.clearDrawables', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=646,
  serialized_end=746,
)

_SHAPEDRAWABLE.fields_by_name['line_style'].enum_type = _SHAPEDRAWABLE_LINESTYLE
_SHAPEDRAWABLE.fields_by_name['fill_pattern'].enum_type = _SHAPEDRAWABLE_FILLPATTERN
_SHAPEDRAWABLE.fields_by_name['shape_type'].enum_type = _SHAPEDRAWABLE_SHAPETYPE
_SHAPEDRAWABLE_FILLPATTERN.containing_type = _SHAPEDRAWABLE;
_SHAPEDRAWABLE_LINESTYLE.containing_type = _SHAPEDRAWABLE;
_SHAPEDRAWABLE_SHAPETYPE.containing_type = _SHAPEDRAWABLE;
_DRAWABLEFRAME.fields_by_name['shapes'].message_type = _SHAPEDRAWABLE
DESCRIPTOR.message_types_by_name['ShapeDrawable'] = _SHAPEDRAWABLE
DESCRIPTOR.message_types_by_name['DrawableFrame'] = _DRAWABLEFRAME

class ShapeDrawable(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SHAPEDRAWABLE
  
  # @@protoc_insertion_point(class_scope:ShapeDrawable)

class DrawableFrame(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DRAWABLEFRAME
  
  # @@protoc_insertion_point(class_scope:DrawableFrame)

# @@protoc_insertion_point(module_scope)
