# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import Drawable_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='GraspitMessage.proto',
  package='',
  serialized_pb='\n\x14GraspitMessage.proto\x1a\x0e\x44rawable.proto\"@\n\x16GraspitProtobufMessage\x12&\n\x0e\x64rawable_frame\x18\x01 \x01(\x0b\x32\x0e.DrawableFrame')




_GRASPITPROTOBUFMESSAGE = descriptor.Descriptor(
  name='GraspitProtobufMessage',
  full_name='GraspitProtobufMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='drawable_frame', full_name='GraspitProtobufMessage.drawable_frame', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=104,
)

_GRASPITPROTOBUFMESSAGE.fields_by_name['drawable_frame'].message_type = Drawable_pb2._DRAWABLEFRAME
DESCRIPTOR.message_types_by_name['GraspitProtobufMessage'] = _GRASPITPROTOBUFMESSAGE

class GraspitProtobufMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GRASPITPROTOBUFMESSAGE
  
  # @@protoc_insertion_point(class_scope:GraspitProtobufMessage)

# @@protoc_insertion_point(module_scope)
