// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "GraspitMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* GraspitProtobufMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GraspitProtobufMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_GraspitMessage_2eproto() {
  protobuf_AddDesc_GraspitMessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "GraspitMessage.proto");
  GOOGLE_CHECK(file != NULL);
  GraspitProtobufMessage_descriptor_ = file->message_type(0);
  static const int GraspitProtobufMessage_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GraspitProtobufMessage, drawable_frame_),
  };
  GraspitProtobufMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GraspitProtobufMessage_descriptor_,
      GraspitProtobufMessage::default_instance_,
      GraspitProtobufMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GraspitProtobufMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GraspitProtobufMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(GraspitProtobufMessage));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_GraspitMessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GraspitProtobufMessage_descriptor_, &GraspitProtobufMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_GraspitMessage_2eproto() {
  delete GraspitProtobufMessage::default_instance_;
  delete GraspitProtobufMessage_reflection_;
}

void protobuf_AddDesc_GraspitMessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_Drawable_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024GraspitMessage.proto\032\016Drawable.proto\"@"
    "\n\026GraspitProtobufMessage\022&\n\016drawable_fra"
    "me\030\001 \001(\0132\016.DrawableFrame", 104);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "GraspitMessage.proto", &protobuf_RegisterTypes);
  GraspitProtobufMessage::default_instance_ = new GraspitProtobufMessage();
  GraspitProtobufMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_GraspitMessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_GraspitMessage_2eproto {
  StaticDescriptorInitializer_GraspitMessage_2eproto() {
    protobuf_AddDesc_GraspitMessage_2eproto();
  }
} static_descriptor_initializer_GraspitMessage_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int GraspitProtobufMessage::kDrawableFrameFieldNumber;
#endif  // !_MSC_VER

GraspitProtobufMessage::GraspitProtobufMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void GraspitProtobufMessage::InitAsDefaultInstance() {
  drawable_frame_ = const_cast< ::DrawableFrame*>(&::DrawableFrame::default_instance());
}

GraspitProtobufMessage::GraspitProtobufMessage(const GraspitProtobufMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void GraspitProtobufMessage::SharedCtor() {
  _cached_size_ = 0;
  drawable_frame_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GraspitProtobufMessage::~GraspitProtobufMessage() {
  SharedDtor();
}

void GraspitProtobufMessage::SharedDtor() {
  if (this != default_instance_) {
    delete drawable_frame_;
  }
}

void GraspitProtobufMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GraspitProtobufMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GraspitProtobufMessage_descriptor_;
}

const GraspitProtobufMessage& GraspitProtobufMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_GraspitMessage_2eproto();  return *default_instance_;
}

GraspitProtobufMessage* GraspitProtobufMessage::default_instance_ = NULL;

GraspitProtobufMessage* GraspitProtobufMessage::New() const {
  return new GraspitProtobufMessage;
}

void GraspitProtobufMessage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_drawable_frame()) {
      if (drawable_frame_ != NULL) drawable_frame_->::DrawableFrame::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool GraspitProtobufMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .DrawableFrame drawable_frame = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_drawable_frame()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void GraspitProtobufMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .DrawableFrame drawable_frame = 1;
  if (has_drawable_frame()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->drawable_frame(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* GraspitProtobufMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .DrawableFrame drawable_frame = 1;
  if (has_drawable_frame()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->drawable_frame(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int GraspitProtobufMessage::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .DrawableFrame drawable_frame = 1;
    if (has_drawable_frame()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->drawable_frame());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GraspitProtobufMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const GraspitProtobufMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const GraspitProtobufMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GraspitProtobufMessage::MergeFrom(const GraspitProtobufMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_drawable_frame()) {
      mutable_drawable_frame()->::DrawableFrame::MergeFrom(from.drawable_frame());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void GraspitProtobufMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GraspitProtobufMessage::CopyFrom(const GraspitProtobufMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GraspitProtobufMessage::IsInitialized() const {
  
  if (has_drawable_frame()) {
    if (!this->drawable_frame().IsInitialized()) return false;
  }
  return true;
}

void GraspitProtobufMessage::Swap(GraspitProtobufMessage* other) {
  if (other != this) {
    std::swap(drawable_frame_, other->drawable_frame_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata GraspitProtobufMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GraspitProtobufMessage_descriptor_;
  metadata.reflection = GraspitProtobufMessage_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
