// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GraspitMessage.proto

#ifndef PROTOBUF_GraspitMessage_2eproto__INCLUDED
#define PROTOBUF_GraspitMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "Drawable.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_GraspitMessage_2eproto();
void protobuf_AssignDesc_GraspitMessage_2eproto();
void protobuf_ShutdownFile_GraspitMessage_2eproto();

class GraspitProtobufMessage;

// ===================================================================

class GraspitProtobufMessage : public ::google::protobuf::Message {
 public:
  GraspitProtobufMessage();
  virtual ~GraspitProtobufMessage();
  
  GraspitProtobufMessage(const GraspitProtobufMessage& from);
  
  inline GraspitProtobufMessage& operator=(const GraspitProtobufMessage& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GraspitProtobufMessage& default_instance();
  
  void Swap(GraspitProtobufMessage* other);
  
  // implements Message ----------------------------------------------
  
  GraspitProtobufMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GraspitProtobufMessage& from);
  void MergeFrom(const GraspitProtobufMessage& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .DrawableFrame drawable_frame = 1;
  inline bool has_drawable_frame() const;
  inline void clear_drawable_frame();
  static const int kDrawableFrameFieldNumber = 1;
  inline const ::DrawableFrame& drawable_frame() const;
  inline ::DrawableFrame* mutable_drawable_frame();
  inline ::DrawableFrame* release_drawable_frame();
  
  // @@protoc_insertion_point(class_scope:GraspitProtobufMessage)
 private:
  inline void set_has_drawable_frame();
  inline void clear_has_drawable_frame();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::DrawableFrame* drawable_frame_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_GraspitMessage_2eproto();
  friend void protobuf_AssignDesc_GraspitMessage_2eproto();
  friend void protobuf_ShutdownFile_GraspitMessage_2eproto();
  
  void InitAsDefaultInstance();
  static GraspitProtobufMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// GraspitProtobufMessage

// optional .DrawableFrame drawable_frame = 1;
inline bool GraspitProtobufMessage::has_drawable_frame() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GraspitProtobufMessage::set_has_drawable_frame() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GraspitProtobufMessage::clear_has_drawable_frame() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GraspitProtobufMessage::clear_drawable_frame() {
  if (drawable_frame_ != NULL) drawable_frame_->::DrawableFrame::Clear();
  clear_has_drawable_frame();
}
inline const ::DrawableFrame& GraspitProtobufMessage::drawable_frame() const {
  return drawable_frame_ != NULL ? *drawable_frame_ : *default_instance_->drawable_frame_;
}
inline ::DrawableFrame* GraspitProtobufMessage::mutable_drawable_frame() {
  set_has_drawable_frame();
  if (drawable_frame_ == NULL) drawable_frame_ = new ::DrawableFrame;
  return drawable_frame_;
}
inline ::DrawableFrame* GraspitProtobufMessage::release_drawable_frame() {
  clear_has_drawable_frame();
  ::DrawableFrame* temp = drawable_frame_;
  drawable_frame_ = NULL;
  return temp;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GraspitMessage_2eproto__INCLUDED
